POST http://localhost:4000/addStudent
Content-Type: application/json

{
    "fName":"Monika",
    "lName":"Kumari",
    "studentID":"20022015",
    "section":"E",
    "password":"monXYZ",
    "imgUrl":"https://drive.google.com/file/d/1rmRTex8BYhe7nQoaP1XukKLJYFY6KWR5/view?usp=sharing"
}